language: node_js
node_js:
- '6.9'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
script:
- npm run lint
- npm test
- npm run build
after_success:
- tools/deploy.sh
env:
  global:
  - secure: ZEJA1/HZcpLh+sUAPW2MshehFKjFlYDpLYfiiZ2NIn4/Nn3eETbjg6EvX/8MnIl3j7rFrepr8WWKF3OdUgEvb6Gutyboam/lWp2R7aevxYLp3BPqY0vygxGW5lHHW2cP6LFMuGWcrlw1yLs/x3fIbqWHTrfXlNqbXR1pRk7iE40w4++QtyDbjYkr/A7Ckzd2OA4flecllyVikgSgac/o8XAQVt1hWO4Mz26gUELs5xT/T8SPssliqZ9D6fuMZYxiuBGgOpmW04+IC4sju6UuawSGkXXK6lbgh6bLaOOarrSD1J+ueZRZK2S7DL1vLIt+i+No8u4XAQi6oZViGgtT9nqCaa+T8xCH/zgNWtFu0fxU26lBOPODqjmXlRUgfUTA/xPDbAyTVvWpa0DdYanHT2qaY9CBhy6WLrhaxt+hsL0weE92KluJn2RZ0szhnt6B8PgvCgeHWO7P4pz781qn8LAJsJSD6Bbh7ObiJ4/9FCjtHAw3/u93nRuqoDn97PDajfnSv538oZ0Lq8nh9iUzLEjq4K45LSsK+wNDGAKqQaJVU5knLntK6fbXLVc0BQSFvuZJOuKsteZx4Ln0za5uTaSpOqfV2q4lkGqeF6wxXFD8Qm07jeMnV0UBkLyjsEg+mIlqktBwBomPGNkjqa4PTmlmzNC6NozfQyB64cCGB0w=
  - secure: iOLipmHffA9XiKI4vMjYkivJP/9Q8Cgnp1ml/EPjSHlwa4NkHiz6GdTXDWrA/cbZLBIHmEmF1Cqe3B5mWHxmpLq6BMZxUYLfv4Nv6cHJ6psMBZ59o7cvo4y0FEj7Riu4MoUy28u+W6UW6It6PtKjSJCXI58LTn0uktmlIXo1AyDbCecLJCkQ1PU+cHC29sxxWlK+B2+sKMRKxVyUE3+VpG2TQ00UhvI0khxFkITzxbOODPAmSzvpDrAv8AROpFQaXoFKhI2hT3pHTLgwyc+KbtTm/A4uMfVtuLspftIjuTGQ3xT3HtBdvCYTLEFMcgODWfMATAzOulpDg24sj6RW5a/SezXFZeG3giubrMqAaHGTjl/i2yndGzMEAnvTkx7qvztk4VlctigbHqVALF3BRyczZ4ZRu113jJQLeuBgzo9piD+BFJGzyDaXSJhGXl1DTzShvEOZpe40uj0urJABX8PSg4qHqMQluev5LWXOK5EjfnbxRv79q0kV3C9GlloNxuQ+tCPCRxBMnycqHKl3jEmjmntJK9HYM7jPtDikgTkYYcB2KllneQUw9Ri0lPVYbnkLLMvS7mFT8Lajz99woeJ9RhG8McuO9KfLi+FLumPuTG/J3skxvlINIJq+X1h0c9gWC0Kv5mh0k/0rM0FuZWIQ52jcGMSwDQ/e/V+X5DY=
